name: run_tests
on:
  push:
    paths:
      - "**.py"
      - "Makefile"
      - "openbabel/**"
      - "eigen/**"
      - "src/**"
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build project
        run: make init
      - name: Unit Tests
        run: make test
      - name: Integration Tests
        run: |
          tests/check_intermediate.sh
          python set_paths.py
          pip install .
          make pytest
